const LIST_COMMODITIES='LIST_COMMODITIES'
// const GET_DELETEDCUSTOMERS='GET_DELETEDCUSTOMERS'
// const GET_SALESTRATEGIES='GET_SALESTRATEGIES'
// const GET_SALECATEGORIES='GET_SALECATEGORIES'
// const GET_USER='GET_USER'
// const GET_SALEHISTORY='GET_SALEHISTORY'
// const GET_RECHARGEHISTORY='GET_RECHARGEHISTORY'
// const GET_CUSTOMERFEEDETAILS='GET_CUSTOMERFEEDETAILS'

export default {
  LIST_COMMODITIES,
  // GET_DELETEDCUSTOMERS,
  // GET_SALESTRATEGIES,
  // GET_SALECATEGORIES,
  // GET_USER,
  // GET_SALEHISTORY,
  // GET_RECHARGEHISTORY,
  // GET_CUSTOMERFEEDETAILS
}
